features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://photo_2017-11-17_01-20-00 (2).jpg'
favicon:
  use_default: 1
