variables:
  colors:
    primaryColor1: 3A3A3A
    primaryColor2: 5A5A5A
    primaryColor3: CCCCCC
    primaryColor4: 1A1A1A
    primaryColor5: 9A9A9A
    mainMenuBgColor: 9A9A9A
    mainMenuFontColor: 1A1A1A
    mainMenuBorderColor: 1A1A1A
    buttonBgColor: 9A9A9A
    buttonFontColor: 1A1A1A
    buttonBorderColor: 1A1A1A
  fonts:
    defaultHeaderFont: georgia
    defaultBodyFont: helvetica
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: true
  path: ''
favicon:
  use_default: false
  path: 'public://Google-Chrome-icon.png'
  mimetype: image/png
omega_toggle_intro: 1
enable_backups: 0
force_subtheme_creation: 0
block_demo_mode: 0
screen_demo_indicator: 0
default_layout: primary
home_layout: primary
enable_omegags_layout: 1
layouts: {  }
breakpoint_group_primary: test.default
node_type_article_layout: primary
node_type_page_layout: primary
taxonomy_category_layout: primary
taxonomy_tags_layout: primary
edit_this_layout: primary
_core:
  default_config_hash: KqRh1wQaJ9MBCkWLh8ymoV6pqPkjLT1SC_sBt8pmLyM
compile_scss: 1
show_compile_warning: 1
enable_omega_badge: 1
styles:
  test/test: 1
  omega/omega: 1
  omega/omega_html_elements: 1
  omega/omega_branding: 1
  omega/omega_breadcrumbs: 1
  omega/omega_main_menus: 1
  omega/omega_messages: 1
  omega/omega_pagers: 1
  omega/omega_tabs: 1
  omega/omega_taxonomy_terms: 1
  omega/omega_forms: 1
  omega_simple_starterkit/omega_simple_starterkit: 1
